# This contains params to be used by the stages to train or predict

prepare:
  split: 0.2
  seed: 2021

featurize:
  max_features: 2500
  ngram_range: 3

train:
  seed: 2021
  n_estimators: 110
  min_split: 32
