# This contains params to be used by the stages to train or predict

prepare:
  split: 0.3
  seed: 42

featurize:
  max_features: 3000
  ngram_range: 2

train:
  seed: 42
  n_estimators: 100
  min_split: 15
